---
- name: Pre satellite disks
  hosts: all 
  become: true
  tasks:
    - name: Create partition on additional disk
      community.general.parted:
        device: /dev/sdb
        number: 1
        flags: "[ lvm ]"
        part_end: "100%"
        state: present

    - name: Create a volume group on top of /dev/sdb1
      community.general.lvg:
        vg: "{{ VG_NAME }}"
        pvs: /dev/sdb1
    - name: Create a logical volume
      community.general.lvol:
        vg: "{{ VG_NAME }}"
        lv: "{{ LV_NAME }}"
        size: 100%FREE

    - name: Create mount point.
      ansible.builtin.file:
        path: "{{ DISK_MOUNTPOINT }}"
        mode: '0755'
        state: directory

    - name: Format disks
      community.general.filesystem:
        fstype: xfs
        dev: "/dev/{{ VG_NAME }}/{{ LV_NAME }}"

    - name: Mount disks
      ansible.posix.mount:
        path: "{{ DISK_MOUNTPOINT }}"
        src: "/dev/{{ VG_NAME }}/{{ LV_NAME }}"
        state: mounted
        fstype: xfs
