---
- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    vcenter_host: "https://vcenter.home.ins"
    cvmname: "{{ lookup('community.general.random_pet', words=3) }}"
    server_role: "Standard"
    server_srf: 12345
    vm_owner: Nasser
    host_disks:
      
    _disks: "{{ DISK_SIZES.split('\n') }}"
    _dns: "{{ VM_DNS.split('\n') }}"
  tasks:
  - name: Create Linux VM from Template
    community.vmware.vmware_guest:
      name: "{{ VMNAME }}" 
      annotation: "{{ server_role }} - Created by Ansible from {{ server_srf }} for {{ vm_owner }}"
      template: "{{ VM_TEMPLATE }}"
      cluster: "{{ VMCLUSTER_NAME }}"
      datacenter: "{{ VMDC_NAME }}"
      folder: "/HomeDC/vm/AAP"
      validate_certs: False
      state: poweredon
      hardware:
        num_cpus: "{{ CPU_COUNT }}"
        memory_mb: "{{ MEMORY_GB * 1024 | int }}"
      disk:
      - type: thin
        size_gb: 40
        datastore: "Datastore-truenas"
      - type: thin
        size_gb: "{{ DISK_SIZE_1 }}"
        datastore: "Datastore-truenas"
      networks:
        - name: "{{ VMNET_NAME }}" 
          type: static
          ip: "{{ VM_IP }}"
          netmask: "{{ VM_SUBNET_MASK }}"
          gateway: "{{ VM_GATEWAY }}"
          dns_servers: "{{ VM_DNS }}"
          connected: true
          start_connected: true
      customization:
        dns_servers: "{{ VM_DNS }}"
        domain: "{{ VM_DOMAIN }}"
      wait_for_ip_address: true
      wait_for_ip_address_timeout: 300
      wait_for_customization: true
      wait_for_customization_timeout: 300
    delegate_to: localhost
    
#  - name: Add VM to AAP
#    ansible.controller.host:
#      controller_host: 10.0.0.119 
#      validate_certs: no
#      name: "{{ VMNAME }}"
#      inventory: "Deployed by AAP"
#      state: present
#      enabled: true
#      variables: 
#        Criticality: "No" #Always No from our side
#        Owner: "{{ vm_owner }}"
#        Notes: "{{ server_role }}"
#    delegate_to: localhost
 
 
