---
- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    vcenter_host: "https://vcenter.home.ins"
    cvmname: "{{ lookup('community.general.random_pet', words=3) }}"
    server_role: "Standard"
    server_srf: 12345
    vm_owner: Nasser
    _disks: "{{ DISK_SIZES.split('\n') }}"
    _dns: "{{ VM_DNS.split('\n') }}"
  tasks:
  - name: Create Linux VM from Template
    community.vmware.vmware_guest:
      name: "{{ VMNAME }}" 
      annotation: "{{ server_role }} - Created by Ansible from {{ server_srf }} for {{ vm_owner }}"
      template: "{{ VM_TEMPLATE }}"
      cluster: "{{ VMCLUSTER_NAME }}"
      datacenter: "{{ VMDC_NAME }}"
      folder: "/HomeDC/vm/AAP"
      validate_certs: False
      state: poweredon
      hardware:
        num_cpus: "4"
        memory_mb: "4096"
      disks:
        - type: thin
          size_gb: 50
          datastore: "Datastore-truenas"
      networks:
        - name: "{{ VMNET_NAME }}" 
          type: static
          ip: "{{ VM_IP }}"
          netmask: "{{ VM_SUBNET }}"
          gateway: "{{ VM_GATEWAY }}"
          dns_servers: 
          - "{{ _dns[0] }}"
          - "{{ _dns[1] }}"
          wait_for_ip_address: true
          wait_for_ip_address_timeout: 300
          connected: true
          start_connected: true
      customization:
        dns_servers: 
        - "{{ _dns[0] }}"
        - "{{ _dns[1] }}"
        domain: "{{ VM_DOMAIN }}"
      wait_for_customization: true
      wait_for_customization_timeout: 300
    delegate_to: localhost

  - name: Create Disks for VM
    community.vmware.vmware_guest_disk:
      name: "{{ VMNAME }}" 
      datacenter: "{{ VMDC_NAME }}"
      folder: "/HomeDC/vm/AAP"
      disks:
        - type: thin
          size_gb: "{{ item }}"
          datastore: "Datastore-truenas"
          state: present
      loop: "{{ _disks }}"

