---
- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: yes
  vars:
    vcenter_host: "https://vcenter.home.ins"
    cvmname: "{{ lookup('community.general.random_pet', words=3) }}"
    server_role: "Standard"
    server_srf: 12345
    vm_owner: Nasser
    host_disks:
      
    _disks: "{{ DISK_SIZES.split('\n') }}"
    _dns: "{{ VM_DNS.split('\n') }}"
  tasks:
  - name: Create Linux VM from Template
    community.vmware.vmware_guest:
      name: "{{ VMNAME }}" 
      annotation: "{{ server_role }} - Created by Ansible from {{ server_srf }} for {{ vm_owner }}"
      template: "{{ VM_TEMPLATE }}"
      cluster: "{{ VMCLUSTER_NAME }}"
      datacenter: "{{ VMDC_NAME }}"
      folder: "/HomeDC/vm/AAP"
      validate_certs: False
      state: poweredon
      hardware:
        num_cpus: "4"
        memory_mb: "4096"
      disk:
      - type: thin
        size_gb: 50
        datastore: "Datastore-truenas"
      - type: thin
        size_gb: "{{ DISK_SIZE_1 }}"
        datastore: "Datastore-truenas"
      networks:
        - name: "{{ VMNET_NAME }}" 
          type: static
          ip: "{{ VM_IP }}"
          netmask: "{{ VM_SUBNET }}"
          gateway: "{{ VM_GATEWAY }}"
          dns_servers: "{{ VM_DNS }}"
          connected: true
          start_connected: true
      customization:
        dns_servers: "{{ VM_DNS }}"
        domain: "{{ VM_DOMAIN }}"
      wait_for_ip_address: true
      wait_for_ip_address_timeout: 300
      wait_for_customization: true
      wait_for_customization_timeout: 300
    delegate_to: localhost
#  - name: Add disks to virtual machine using VM name
#    vmware_guest_disk:
#      name: "{{ VMNAME }}"
#      disk:
#      - size_gb: "{{ item.0 }}"
#        type: thin
#        datastore: Datastore-truenas
#        state: present
#        scsi_controller: 
#        unit_number: "{{ item.1 }}"
#        scsi_type: 'paravirtual'
#      with_nested:
#        - "{{ _disks }}"
#        - [1, 2, 3, 4, 5, 6, 8, 9, 10, 11, 12, 13, 14]
