---
- name: Deploy RHEL/Debian ISO to VMware
  hosts: localhost
  gather_facts: false
  vars:
    vmparams:
      vcenter_host: "vcenter.home.ins"
      name: "test_vm"
      iso_datastore: "/HomeDC/datastore/Datastore-esxi-01"
      cluster: "cluster"
      os: "RHEL"
      os_iso: ""
    network_params:
      ip_address: "10.0.200.200"
      netmask: "255.255.255.0"
      gateway: "10.0.200.254"
      vm_network: "SharedServices.200"
    default_partitions:
      - mount: "/var"
        size: "{{ var_size | default(5) }}"
      - mount: "/tmp"
        size: "{{ tmp_size | default(5) }}"
  tasks:
    - name: Deploy VM from ISO
      community.vmware.vmware_guest:
       # hostname: "{{ VMWARE_HOST }}"
       # username: "{{ VMWARE_USER }}"
       # password: "{{ VMWARE_PASSWORD }}"
        validate_certs: false
        name: "{{ vmparams.name }}"
        state: poweredon
        guest_id: "rhel9_64Guest" # Adjust for RHEL/Debian version
        iso:
          datastore: "{{ vmparams.iso_datastore }}"
          path: "{{ iso_datastore }}/{{ vmparams.os_iso }}"
        networks:
          - name: "{{ network_params.vm_network }}"
            ip: "{{ network_params.ip_address }}"
            netmask: "{{ network_params.netmask }}"
            gateway: "{{ network_params.gateway }}"
        hardware:
          memory_mb: "4096"
          num_cpus: "2"
          scsi:
            - type: "paravirtual"
              disks:
                - size_gb: "40"
                  type: "thin"
                  datastore: "{{ vmparams.iso_datastore }}"
                  #            - name: "Default Partitions"
                  #              size_gb: "{{ item.size }}"
                  #              datastore: "{{ vmparams.iso_datastore }}"
                  #              type: "thin"
                  #        mount: "{{ item.mount }}"
                  #        with_items: "{{ default_partitions }}"
                  #        - name: "Additional Disks"
                  #          size_gb: "{{ item.size }}"
                  #          datastore: "{{ vmparams.iso_datastore }}"
                  #          type: "thin"
                  #          mount: "{{ item.mount }}"
                  #          with_items: "{{ additional_disks }}"
                  #       - name: Configure partitions and mount points
                  #         block:
                  #        - name: Create LVM volume group for each disk
                  #          lvg:
                  #            vg: "vg_{{ item.mount.split('/')\[-1\] }}"
                  #            pvs: "/dev/sd{{ loop.index }}"
                  #          loop: "{{ default_partitions + additional_disks }}"
                  #        - name: Create logical volume and format
                  #          lvol:
                  #            vg: "vg_{{ item.mount.split('/')\[-1\] }}"
                  #            lv: "lv_{{ item.mount.split('/')\[-1\] }}"
                  #            size: "{{ item.size }}"
                  #            filesystem: ext4
                  #            loop: "{{ default_partitions + additional_disks }}"
                  #        - name: Update /etc/fstab
                  #          lineinfile:
                  #            path: /etc/fstab
                  #            line: "/dev/vg_{{ item.mount.split('/')\[-1\] }}/lv_{{ item.mount.split('/')\[-1\] }} {{ item.mount }} ext4 defaults 0 2"
                  #            loop: "{{ default_partitions + additional_disks }}"
                  #        - name: Mount partitions
                  #          mount:
                  #            path: "{{ item.mount }}"
                  #            src: "/dev/vg_{{ item.mount.split('/')\[-1\] }}/lv_{{ item.mount.split('/')\[-1\] }}"
                  #            fstype: ext4
                  #          state: mounted
                  #          loop: "{{ default_partitions + additional_disks }}"
