---
- name: Create a VM from a template
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    vcenter_host: "https://vcenter.home.ins"
    cvmname: "{{ lookup('community.general.random_pet', words=3) }}"
    server_role: "Standard"
    server_srf: 12345
    vm_owner: Nasser
    _disks: "{{ DISK_SIZES.split('\n') }}"
    _dns: "{{ VM_DNS.split('\n') }}"
  tasks:
  - name: Create Linux VM from Template
    community.vmware.vmware_guest:
      name: "{{ VMNAME }}" 
      annotation: "{{ server_role }} - Created by Ansible from {{ server_srf }} for {{ vm_owner }}"
      template: "{{ VM_TEMPLATE }}"
      cluster: "{{ VMCLUSTER_NAME }}"
      datacenter: "{{ VMDC_NAME }}"
      folder: "/HomeDC/vm/AAP"
      validate_certs: False
      state: poweredon
      hardware:
        num_cpus: "4"
        memory_mb: "4096"
      disk:
      - type: thin
        size_gb: 50
        datastore: "Datastore-truenas"
      networks:
        - name: "{{ VMNET_NAME }}" 
          type: static
          ip: "{{ VM_IP }}"
          netmask: "{{ VM_SUBNET }}"
          gateway: "{{ VM_GATEWAY }}"
          dns_servers: 
          - "{{ item }}"
          wait_for_ip_address: true
          wait_for_ip_address_timeout: 300
          connected: true
          start_connected: true
      customization:
        dns_servers: 
        - "{{ item }}"
        domain: "{{ VM_DOMAIN }}"
      wait_for_customization: true
      wait_for_customization_timeout: 300
    loop: "{{ _dns }}"
    delegate_to: localhost
    register: vm_info

  - name: Calculate next available unit_number
    set_fact:
      next_unit_number: "{{ vm_info.instance.hardware_devices.disks | length }}"
      reserved_numbers: [7]  # Reserved unit numbers (e.g., for SCSI controllers)
      available_unit_numbers: "{{ range(0, 15) | difference(reserved_numbers) }}"
      next_unit_number: >-
        {{
          available_unit_numbers[
            (vm_info.instance.hardware_devices.disks | length) % available_unit_numbers | length
          ]
        }}
  - name: Create Disks for VM
    community.vmware.vmware_guest_disk:
      name: "{{ VMNAME }}" 
      datacenter: "{{ VMDC_NAME }}"
      folder: "/HomeDC/vm/AAP"
      disk:
      - type: thin
        size_gb: "{{ item }}"
        datastore: "Datastore-truenas"
        scsi_controller: 1
        unit_number: "{{ next_unit_number }}"
        state: present
    loop: "{{ _disks }}"

