---
- name: Get disk info
  hosts: all
  gather_facts: yes
  vars:
    root_dev: "{{ ansible_mounts | json_query('[?mount == `/`].device') }}"
  tasks:
    - name: Find OS disk
      ansible.builtin.debug:
        var: root_dev
    - name: Get secondary disk name
      ansible.builtin.debug:
        var: hostvars[inventory_hostname].ansible_devices | map('regex_search', 'sd.*') | select('string') | list
    - name: Configure disks and mount points
      community.general.lvg:
        vg: test_vg
        pvs: 
 
