---
- name: Configure hosts for ansible
  become_user: root
  become: yes
  hosts: all 
  vars:
    #certificate_path: "/root/files/sat.pem"
    satellite_url: satellite.home.ins
    activation_key: "rhel8"
    _org_id: "HomeDC"
  tasks:
#    - name: Trust Corportate CA Certificate
#      copy:
#        src: "{{ certificate_path }}"
#        dest: /etc/pki/ca-trust/source/anchors/
#        owner: root
#        group: root

#    - name: update trust store
#      shell: /usr/bin/update-ca-trust

  - name: Install Katello Package
    yum:
      name: "https://{{ satellite_url }}/pub/katello-ca-consumer-latest.noarch.rpm"
      state: present
      disable_gpg_check: yes

  - name: Register to Satellite
    redhat_subscription:
      state: present
      server_hostname: "{{ satellite_url }}"
    # server_insecure: true
    # username: "admin"
    # password: "P@ssw0rd"
      activationkey: "rhel8"
      org_id: "{{ _org_id }}"
      force_register: yes
    when: 
      - ansible_facts['distribution'] == "RedHat" 
      - ansible_facts['distribution_major_version'] == "8"

  - name: Register to Satellite
    redhat_subscription:
      state: present
      server_hostname: "{{ satellite_url }}"
    # server_insecure: true
    # username: "admin"
    # password: "P@ssw0rd"
      activationkey: "rhel8"
      org_id: "{{ _ord_id }}"
      force_register: yes
    when: 
      - ansible_facts['distribution'] == "RedHat" 
      - ansible_facts['distribution_major_version'] == "9"


