---
version: 3
dependencies: 
  galaxy: requirements.yml
  python: requirements.txt


additional_build_steps:
  prepend_builder:
    - ENV PKGMGR_OPTS="--nodocs --setopt=install_weak_deps=0 --setopt=rhocp-4.14-for-rhel-9-x86_64-rpms.enabled=true"
  prepend_final:
    - ENV PKGMGR_OPTS="--nodocs --setopt=install_weak_deps=0 --setopt=rhocp-4.14-for-rhel-9-x86_64-rpms.enabled=true"

options:
    package_manager_path: /usr/bin/microdnf

images: 
  base_image:
    name: registry.redhat.io/ansible-automation-platform-24/ee-minimal-rhel9:latest
